### PR TITLE
Fix merge logic for Ruby SimpleCov coverage reports

### PR DESCRIPTION
**Pull request by GreyTeardrop**
SimpleCov reports that don't execute any tests targeting some file include 0 for all lines of that file. If another chunk of tests does cover that file, the "proper" report includes `null`s for non-executable lines.

If then multiple reports are fed to SonarQube, existing merge logic merged `null` and 0 into 0, so non-executable lines of code are reported as non-covered.

SimpleCov includes its own [reports merge logic](https://github.com/simplecov-ruby/simplecov/blob/v0.22.0/lib/simplecov/combine/lines_combiner.rb#L20-L40) which merges null and 0 into null.

This change aligns coverage reports merge logic with SimpleCov's own.

### CODE REVIEW

**Comment by colin-sonarsource** [comment]
Adding some links back to our community for context:

https://community.sonarsource.com/t/sonarqube-incorrectly-aggregates-simplecov-ruby-coverage-reports/111845?u=colin
https://community.sonarsource.com/t/coverage-different-much-lower-coverage-in-sonarcloud-for-rails-project/83565

**Comment by andres-martin** [comment]
Hi guys are there any updates on this issue?, we're experiencing the same coverage mismatch in our rails projects

**Comment by tylermikev-kenna** [comment]
Any updates? I'm also facing this issue and its preventing us from being able to use SQ properly.

**Comment by dorian-burihabwa-sonarsource** [comment]
Hey @GreyTeardrop,

I am closing this PR because we worked on [a fix](https://github.com/SonarSource/sonar-ruby/commit/dc3ccbe50e9e63f4ae72accdfd8e180dbbb08e21) for this issue in the [new sonar-ruby repository](https://github.com/SonarSource/sonar-ruby) and it should be shipped with the next release.

**Comment by GreyTeardrop** [comment]
I see, thank you @dorian-burihabwa-sonarsource! Looking forward to seeing that new release. Is that going to be a 10.7 release?

**Comment by dorian-burihabwa-sonarsource** [comment]
Indeed, 10.7 is the target.

**Comment by osbornk** [comment]
Will this functionality be making its way to SonarCloud as well? We are experiencing this bug there.

**Comment by agigleux** [comment]
Yes. Changes are deployed first on SonarCloud before being packaged in a SonarQube version.

**Comment by JulienDefrance** [comment]
@colin-sonarsource @agigleux @dorian-burihabwa-sonarsource Were these changes/fixes ever deployed to SonarCloud? 

I am also experiencing discrepancies between RSpec/SimpleCov (97-98%) and SonarCloud (89-90%) many months later.

**Pull request closed without merging**
